Configurable properties
SUSE/sapwmp pull request #9
Opened 2021-04-01 13:14 UTC by Werkov

I'm posting this for review. The new config options aren't deliberately documented in the conf-file since they shouldn't be officially necessary. Also mind it's still speculative if this is needed at all, so _de_priotize accordingly.

2021-04-13 07:11 UTC, nick-wang requested changes
Great change, except minor issues could be enhanced.

2021-04-13 07:11 UTC, nick-wang commented on src/config.c
> +}
Need return value due to `static int` type.

2021-04-13 07:11 UTC, nick-wang commented on src/config.c
> +}
Same here, need return value.

2021-04-13 07:11 UTC, nick-wang commented on src/config.c
> +}
Same here, need return value.

2021-04-13 07:11 UTC, nick-wang commented on src/config.c
> +}
Need to free `v` when return with 0.

2021-04-15 10:09 UTC, Werkov commented on src/config.c
> +}
Good catch.

2021-04-15 10:11 UTC, Werkov commented
Thanks for the review, I've force-pushed fixes.

2021-04-19 02:16 UTC, nick-wang approved these changes

2021-04-19 02:16 UTC, nick-wang commented
Looks perfect after the changes, ready to merge!

2021-04-19 02:19 UTC, merged